Regressão Logística

Este projeto tem por objetivo desenvolver um algoritmo de Machine Learning para análise da performance de alunos em provas

Os dados foram extraídos do site do Kaggle: https://www.kaggle.com/datasets/whenamancodes/students-performance-in-exams

In [1]:
import numpy as np
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
df = pd.read_csv('/content/drive/MyDrive/DataScience/trab3/exams-tratados1.csv', escapechar='\\', encoding='utf-8')

In [4]:
df.head(7)

gender race/ethnicity parental level of education         lunch  \
0    male        group A                 high school      standard   
1  female        group D            some high school  free/reduced   
2    male        group E                some college  free/reduced   
3    male        group B                 high school      standard   
4    male        group E          associate's degree      standard   
5  female        group D                 high school      standard   
6  female        group A           bachelor's degree      standard   

  test preparation course  math score  reading score  writing score  
0               completed          67             67             63  
1                    none          40             59             55  
2                    none          59             60             50  
3                    none          77             78             68  
4               completed          78             73             68  
5                    none          63             77             76  
6                    none          62             59             63

In [5]:
rep_df = df.replace(["associate's degree", "bachelor's degree", "master's degree"], ["associates degree", "bachelors degree", "masters degree"])
rep_df.head(7)

gender race/ethnicity parental level of education         lunch  \
0    male        group A                 high school      standard   
1  female        group D            some high school  free/reduced   
2    male        group E                some college  free/reduced   
3    male        group B                 high school      standard   
4    male        group E           associates degree      standard   
5  female        group D                 high school      standard   
6  female        group A            bachelors degree      standard   

  test preparation course  math score  reading score  writing score  
0               completed          67             67             63  
1                    none          40             59             55  
2                    none          59             60             50  
3                    none          77             78             68  
4               completed          78             73             68  
5                    none          63             77             76  
6                    none          62             59             63

In [6]:
rep_df.shape

(1000, 8)

In [7]:
# Transformando as variáveis categóricas nominais em variáveis categóricas ordinais
df2 = pd.DataFrame.copy(rep_df)

In [8]:
df2['gender'].replace({'male':0, 'female': 1}, inplace=True)
df2['race/ethnicity'].replace({'group A':0, 'group B': 1, 'group C': 2, 'group D': 3, 'group E': 4}, inplace=True)
df2['lunch'].replace({'standard':0, 'free/reduced': 1}, inplace=True)
df2['test preparation course'].replace({'completed':0, 'none': 1}, inplace=True)
df2['parental level of education'].replace({'some high school':0, 'high school': 1, 'some college': 2, 
                                           'bachelors degree': 3, 'associates degree': 4, 'masters degree': 5}, inplace=True)

In [9]:
df2.head(10)

gender  race/ethnicity  parental level of education  lunch  \
0       0               0                            1      0   
1       1               3                            0      1   
2       0               4                            2      1   
3       0               1                            1      0   
4       0               4                            4      0   
5       1               3                            1      0   
6       1               0                            3      0   
7       0               4                            2      0   
8       0               3                            1      0   
9       0               2                            2      1   

   test preparation course  math score  reading score  writing score  
0                        0          67             67             63  
1                        1          40             59             55  
2                        1          59             60             50  
3                        1          77             78             68  
4                        0          78             73             68  
5                        1          63             77             76  
6                        1          62             59             63  
7                        0          93             88             84  
8                        1          63             56             65  
9                        1          47             42             45

In [10]:
df2.dtypes

gender                         int64
race/ethnicity                 int64
parental level of education    int64
lunch                          int64
test preparation course        int64
math score                     int64
reading score                  int64
writing score                  int64
dtype: object

In [11]:
df2.shape

(1000, 8)

In [12]:
# OneHotEncoder: Criação de variáveis Dummy (fictícia)
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [13]:
encoder = OneHotEncoder()
oneHotEncoder = encoder.fit_transform(df[['gender', 'race/ethnicity', 'parental level of education', 'lunch', 'test preparation course']])

In [14]:
oneHotEncoder.todense()

matrix([[0., 1., 1., ..., 1., 1., 0.],
        [1., 0., 0., ..., 0., 0., 1.],
        [0., 1., 0., ..., 0., 0., 1.],
        ...,
        [1., 0., 0., ..., 0., 0., 1.],
        [1., 0., 0., ..., 1., 0., 1.],
        [0., 1., 1., ..., 1., 1., 0.]])

In [15]:
oneHotEncoder.shape

(1000, 17)

In [16]:
nome_colunas = encoder.get_feature_names(['gender', 'race/ethnicity', 'parental level of education', 'lunch', 'test preparation course'])
df3_encoder = pd.DataFrame(oneHotEncoder.todense(), columns= nome_colunas)
df3_encoder

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


gender_female  gender_male  race/ethnicity_group A  \
0              0.0          1.0                     1.0   
1              1.0          0.0                     0.0   
2              0.0          1.0                     0.0   
3              0.0          1.0                     0.0   
4              0.0          1.0                     0.0   
..             ...          ...                     ...   
995            0.0          1.0                     0.0   
996            0.0          1.0                     0.0   
997            1.0          0.0                     0.0   
998            1.0          0.0                     0.0   
999            0.0          1.0                     1.0   

     race/ethnicity_group B  race/ethnicity_group C  race/ethnicity_group D  \
0                       0.0                     0.0                     0.0   
1                       0.0                     0.0                     1.0   
2                       0.0                     0.0                     0.0   
3                       1.0                     0.0                     0.0   
4                       0.0                     0.0                     0.0   
..                      ...                     ...                     ...   
995                     0.0                     1.0                     0.0   
996                     0.0                     0.0                     1.0   
997                     0.0                     1.0                     0.0   
998                     0.0                     1.0                     0.0   
999                     0.0                     0.0                     0.0   

     race/ethnicity_group E  parental level of education_associate's degree  \
0                       0.0                                             0.0   
1                       0.0                                             0.0   
2                       1.0                                             0.0   
3                       0.0                                             0.0   
4                       1.0                                             1.0   
..                      ...                                             ...   
995                     0.0                                             0.0   
996                     0.0                                             1.0   
997                     0.0                                             0.0   
998                     0.0                                             0.0   
999                     0.0                                             0.0   

     parental level of education_bachelor's degree  \
0                                              0.0   
1                                              0.0   
2                                              0.0   
3                                              0.0   
4                                              0.0   
..                                             ...   
995                                            0.0   
996                                            0.0   
997                                            0.0   
998                                            0.0   
999                                            0.0   

     parental level of education_high school  \
0                                        1.0   
1                                        0.0   
2                                        0.0   
3                                        1.0   
4                                        0.0   
..                                       ...   
995                                      1.0   
996                                      0.0   
997                                      0.0   
998                                      0.0   
999                                      0.0   

     parental level of education_master's degree  \
0                                            0.0   
1                                            0.0   
2               

In [17]:
df3 = pd.concat([df, df3_encoder], axis=1).drop(['gender', 'race/ethnicity', 'parental level of education', 'lunch', 'test preparation course'], axis=1)
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 20 columns):
 #   Column                                          Non-Null Count  Dtype  
---  ------                                          --------------  -----  
 0   math score                                      1000 non-null   int64  
 1   reading score                                   1000 non-null   int64  
 2   writing score                                   1000 non-null   int64  
 3   gender_female                                   1000 non-null   float64
 4   gender_male                                     1000 non-null   float64
 5   race/ethnicity_group A                          1000 non-null   float64
 6   race/ethnicity_group B                          1000 non-null   float64
 7   race/ethnicity_group C                          1000 non-null   float64
 8   race/ethnicity_group D                          1000 non-null   float64
 9   race/ethnicity_group E                    

Legenda:

Gender: Gênero

Race/Ethnicity: Raça ou etnia

Parental Level of Education: Nível de escolaridade dos pais

Luch: Almoço (se era padrão ou de graça/reduzido)

Test Preparation Course: Curso preparatório para testes - sem é completo ou se não tem

Math Score: Pontuação em matemática

Reading Score: Pontuação em leitura

Writing Score: Pontuação em escrita

In [18]:
# ATRIBUTOS PREVISORES E ALVO
df2.head()

gender  race/ethnicity  parental level of education  lunch  \
0       0               0                            1      0   
1       1               3                            0      1   
2       0               4                            2      1   
3       0               1                            1      0   
4       0               4                            4      0   

   test preparation course  math score  reading score  writing score  
0                        0          67             67             63  
1                        1          40             59             55  
2                        1          59             60             50  
3                        1          77             78             68  
4                        0          78             73             68

In [20]:
previsores = df2.iloc[:, 0:8].values
previsores

array([[ 0,  0,  1, ..., 67, 67, 63],
       [ 1,  3,  0, ..., 40, 59, 55],
       [ 0,  4,  2, ..., 59, 60, 50],
       ...,
       [ 1,  2,  0, ..., 32, 35, 41],
       [ 1,  2,  2, ..., 73, 74, 82],
       [ 0,  0,  2, ..., 65, 60, 62]])

In [21]:
previsores.shape

(1000, 8)

In [22]:
alvo = df2.iloc[:, 7].values
alvo

array([ 63,  55,  50,  68,  68,  76,  63,  84,  65,  45,  85,  90,  85,
        73,  85,  57,  42,  65,  44,  31,  88,  55,  73,  54,  32,  42,
        56,  60,  89,  51,  77,  73,  39,  71,  89,  74,  75,  54,  73,
        77,  72,  64,  82,  70,  87,  51,  57,  78,  73,  57,  64,  60,
        85,  49,  47,  62,  84,  83,  51,  48,  68,  59,  62,  78,  97,
        70,  56,  49,  60,  57,  73,  47,  63,  81,  67,  70,  59,  81,
        76,  45,  62,  42,  59,  73,  39,  69,  69,  88,  61,  72,  42,
        70,  87,  93,  72,  67, 100,  49,  49,  53,  62,  79,  77,  67,
        58,  82,  73,  44,  71,  33,  86,  47,  71,  33,  74,  76,  63,
        55,  58,  87,  71,  89,  62,  45,  86,  58,  64,  45,  87, 100,
        82,  64,  57,  56,  54,  69,  76,  68,  49,  64,  57,  83,  87,
        60,  68,  57,  66,  46, 100,  44,  80,  59,  76,  73,  58,  47,
        59,  87,  93,  79,  97,  65,  91,  75,  70,  92,  58,  68,  93,
        83,  59,  76,  71,  62,  72,  60,  56,  51,  95,  86,  6

In [23]:
alvo.shape

(1000,)

In [24]:
# Análise das escalas dos atributos (Escalonamento)
df2.describe()

gender  race/ethnicity  parental level of education        lunch  \
count  1000.000000     1000.000000                  1000.000000  1000.000000   
mean      0.483000        2.161000                     2.144000     0.348000   
std       0.499961        1.132414                     1.581697     0.476574   
min       0.000000        0.000000                     0.000000     0.000000   
25%       0.000000        1.000000                     1.000000     0.000000   
50%       0.000000        2.000000                     2.000000     0.000000   
75%       1.000000        3.000000                     4.000000     1.000000   
max       1.000000        4.000000                     5.000000     1.000000   

       test preparation course   math score  reading score  writing score  
count              1000.000000  1000.000000    1000.000000    1000.000000  
mean                  0.665000    66.396000      69.002000      67.738000  
std                   0.472227    15.402871      14.737272      15.600985  
min                   0.000000    13.000000      27.000000      23.000000  
25%                   0.000000    56.000000      60.000000      58.000000  
50%                   1.000000    66.500000      70.000000      68.000000  
75%                   1.000000    77.000000      79.000000      79.000000  
max                   1.000000   100.000000     100.000000     100.000000

In [25]:
from sklearn.preprocessing import StandardScaler

In [26]:
previsores_esc = StandardScaler().fit_transform(previsores)

In [27]:
previsores_esc

array([[-0.96655883, -1.90926764, -0.72363566, ...,  0.03923309,
        -0.13591401, -0.30385073],
       [ 1.03459817,  0.74126587, -1.35618431, ..., -1.714564  ,
        -0.67902695, -0.81689543],
       [-0.96655883,  1.62477704, -0.09108701, ..., -0.48041049,
        -0.61113783, -1.13754838],
       ...,
       [ 1.03459817, -0.1422453 , -1.35618431, ..., -2.23420758,
        -2.30836575, -1.71472367],
       [ 1.03459817, -0.1422453 , -0.09108701, ...,  0.42896578,
         0.33930981,  0.91463045],
       [-0.96655883, -1.90926764, -0.09108701, ..., -0.0906778 ,
        -0.61113783, -0.36798132]])

In [28]:
previsoresdf = pd.DataFrame(previsores_esc)
previsoresdf

0         1         2         3         4         5         6  \
0   -0.966559 -1.909268 -0.723636 -0.730577 -1.408927  0.039233 -0.135914   
1    1.034598  0.741266 -1.356184  1.368782  0.709760 -1.714564 -0.679027   
2   -0.966559  1.624777 -0.091087  1.368782  0.709760 -0.480410 -0.611138   
3   -0.966559 -1.025756 -0.723636 -0.730577  0.709760  0.688788  0.610866   
4   -0.966559  1.624777  1.174010 -0.730577 -1.408927  0.753743  0.271421   
..        ...       ...       ...       ...       ...       ...       ...   
995 -0.966559 -0.142245 -0.723636 -0.730577  0.709760  0.428966  0.067753   
996 -0.966559  0.741266  1.174010  1.368782 -1.408927  1.208431  1.493425   
997  1.034598 -0.142245 -1.356184  1.368782  0.709760 -2.234208 -2.308366   
998  1.034598 -0.142245 -0.091087 -0.730577  0.709760  0.428966  0.339310   
999 -0.966559 -1.909268 -0.091087 -0.730577 -1.408927 -0.090678 -0.611138   

            7  
0   -0.303851  
1   -0.816895  
2   -1.137548  
3    0.016802  
4    0.016802  
..        ...  
995 -0.175590  
996  1.555936  
997 -1.714724  
998  0.914630  
999 -0.367981  

[1000 rows x 8 columns]

In [29]:
# BASE DE TREINO E TESTE
from sklearn.model_selection import train_test_split

In [30]:
x_treino, x_teste, y_treino, y_teste = train_test_split(previsores_esc, alvo, test_size = 0.3, random_state = 0)

In [31]:
x_treino.shape

(700, 8)

In [32]:
y_treino.shape

(700,)

In [33]:
x_teste.shape

(300, 8)

In [34]:
y_teste.shape

(300,)

Regressão logística

In [35]:
from sklearn.linear_model import LogisticRegression

In [36]:
logistica = LogisticRegression(random_state=1, max_iter=500, penalty="l2",
                               tol=0.0001, C=2,solver="lbfgs")
logistica.fit(x_treino, y_treino)

LogisticRegression(C=2, max_iter=500, random_state=1)

In [37]:
logistica.intercept_

array([-6.66035239, -3.8321102 , -4.02431646, -3.6901313 , -4.03839424,
       -4.22858255, -3.90679379, -4.01231339, -3.74000738, -2.39072063,
       -4.11499074, -2.62864467, -3.61890977, -3.25737755, -1.34801383,
       -0.65243486, -0.71122121, -0.98794873, -0.35017593, -0.22728822,
        0.26536357,  0.23387902, -0.17450553,  0.49175721,  0.83478926,
        0.55159124,  2.2118101 ,  1.67379092,  0.94927711,  2.69807287,
        2.27540448,  2.48726551,  3.06684598,  3.20034453,  2.59272339,
        3.44439233,  3.54107159,  4.0149321 ,  3.82592351,  3.84773687,
        3.45732145,  3.87711637,  2.37768235,  3.87782475,  4.06546904,
        3.46278612,  3.39673177,  3.2603355 ,  2.79734585,  3.16655438,
        2.60131006,  2.15552674,  2.13491111,  2.24929553,  2.00059464,
        1.82623439,  1.68041399,  0.93324138,  0.58207022,  0.96914517,
        0.48652351, -1.33539878, -0.5046275 , -0.83245566, -1.24595353,
       -1.42619107, -2.01776471, -2.10324618, -2.94383457, -2.40

In [38]:
logistica.coef_

array([[-2.92550048e-01, -4.56746304e-01, -1.12760608e-01,
         5.64457851e-01,  5.88119155e-01, -2.08995523e+00,
        -2.23305725e+00, -2.80376121e+00],
       [-6.37984886e-01, -6.57648195e-01, -1.76428624e-02,
         7.00974647e-01,  4.37057945e-01, -5.18616327e-01,
        -2.17425186e+00, -2.25884051e+00],
       [-8.13310020e-01,  4.57406689e-02,  1.59488787e-02,
         5.95255601e-01,  4.77438264e-01, -1.17774026e+00,
        -2.24039935e+00, -1.96180732e+00],
       [-8.12766386e-01, -5.24187816e-02, -1.10831244e+00,
         7.47483001e-01,  5.46525774e-01, -4.45975537e-01,
        -2.03382827e+00, -2.07876136e+00],
       [-9.12796412e-01, -6.32260946e-01, -9.93569615e-01,
        -8.34261757e-01,  5.58538491e-01, -1.58196023e+00,
        -1.69696468e+00, -1.98581508e+00],
       [-2.71839839e-01, -3.99788715e-03, -4.64566909e-01,
         7.53317085e-01,  6.86205198e-01, -1.50287645e+00,
        -1.95895226e+00, -2.28089108e+00],
       [-1.07277971e+00, -1.952623

In [39]:
previsoes_logistica = logistica.predict(x_teste)
previsoes_logistica

array([ 60,  75,  58,  66,  49,  48,  64,  72,  64, 100,  23,  74,  83,
        76,  74,  64,  84,  66,  73,  89,  69,  83,  66,  47,  79,  64,
        44,  64,  69,  49,  65,  60,  64,  83,  44,  90,  56,  66,  64,
        71,  84,  95,  93,  78,  72,  65,  69,  71,  75,  84,  78,  79,
        48,  66,  78,  73,  63,  79,  78,  80,  72,  64,  87,  65,  61,
        47,  90,  71,  64,  47,  72,  47,  47,  64,  65,  66,  70,  78,
        71,  60,  47,  90,  49,  78,  73,  58,  63,  87,  64,  63,  92,
        64,  58,  73,  88,  86,  33,  72,  64,  48,  39,  65,  70,  76,
        80,  56,  89,  49,  64,  73,  42,  76,  78,  84,  64,  89,  81,
        75,  71,  93, 100,  71,  55,  73,  66,  66,  66,  43,  56,  58,
        64,  66,  95,  52,  56,  84,  44,  64,  74,  60,  73,  53,  76,
        83,  51,  47,  75,  79,  54,  87,  64,  72,  75,  64,  72,  58,
        84,  64,  88,  82,  82,  71,  66,  75,  70,  87,  56,  75,  52,
        60,  60,  51,  60,  95,  48,  97,  84,  85,  65,  78,  8

In [40]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [41]:
print("Acurácia: %.2f%%" % (accuracy_score(y_teste, previsoes_logistica) * 100.0))

Acurácia: 8.67%


In [42]:
confusion_matrix(y_teste, previsoes_logistica)

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 2],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 3]])

In [43]:
print(classification_report(y_teste, previsoes_logistica))

              precision    recall  f1-score   support

          23       0.00      0.00      0.00         0
          27       0.00      0.00      0.00         1
          28       0.00      0.00      0.00         1
          30       0.00      0.00      0.00         1
          33       0.00      0.00      0.00         1
          34       0.00      0.00      0.00         1
          35       0.00      0.00      0.00         1
          36       0.00      0.00      0.00         1
          37       0.00      0.00      0.00         1
          39       0.00      0.00      0.00         2
          40       0.00      0.00      0.00         1
          41       0.00      0.00      0.00         1
          42       0.00      0.00      0.00         0
          43       0.00      0.00      0.00         3
          44       0.00      0.00      0.00         4
          45       0.00      0.00      0.00         3
          47       0.00      0.00      0.00         3
          48       0.00    

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1

In [45]:
# Análise dados de treino
previsoes_treino = logistica.predict(x_treino)
previsoes_treino

array([ 85,  60,  56,  70,  65,  69,  83,  76,  64,  58,  40,  64,  71,
        87,  78,  43,  60,  76,  44,  56,  90,  64,  74,  64,  69,  64,
        71,  72,  63,  83,  63,  84, 100,  47,  84,  63,  85,  72,  64,
        64,  63,  59,  58,  85,  83,  49,  47,  66, 100,  71,  73,  66,
        70,  86,  88,  75,  64,  32,  58,  64,  78,  67,  72,  73,  67,
        83,  73,  56,  81,  64,  75,  60,  61,  66,  58,  40,  71,  43,
        89,  74,  75,  83,  66,  70,  43,  69,  87,  64,  58,  61,  62,
        69,  64,  97,  74,  49,  71,  88,  63,  72,  85,  33,  69,  89,
        51,  75,  87,  58,  97,  83, 100,  64,  65,  71,  42,  86,  71,
        93,  65,  64,  64,  44,  76,  67,  56,  73,  44,  52,  64,  51,
        79,  65,  58,  39,  79,  86,  60,  66,  64,  58,  66,  95,  90,
        64,  59,  66,  35,  78,  47,  84,  72,  64,  83,  83,  86,  49,
        66,  65,  78,  33,  42,  65,  79,  64,  73,  60,  82,  73,  83,
        95,  89,  83,  60,  64,  64,  40,  84,  42,  49,  42,  6

In [46]:
accuracy_score(y_treino, previsoes_treino)

0.26571428571428574

In [47]:
confusion_matrix(y_treino, previsoes_treino)

array([[ 1,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0],
       ...,
       [ 0,  0,  0, ...,  0,  0,  1],
       [ 0,  0,  0, ...,  0,  1,  1],
       [ 0,  0,  0, ...,  0,  0, 14]])